site_name: Python-Unterricht
site_description: Tutorials, Codebeispiele und Aufgaben für den Unterricht

theme:
  name: material
  language: de

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

nav:
  - Startseite: index.md
  - Setup:
      - Installation Python & VS-Code: python-vscode-installation.md
      - VS Code Erste Schritte: vscode-erste-schritte.md
      - Begrüssung: aufgaben/aufgabe-01.md
  - Mini-Games:
      - Übersicht: mini-games/index.md
      - 1. Game Intro: mini-games/01-game-intro.md
      - 2. Variablen & Datentypen: mini-games/02-variablen-datentypen.md
      - 3. Operatoren: mini-games/03-operatoren.md
      - 4. Eingaben: mini-games/04-input.md
      - 5. Verzweigungen: mini-games/05-verzweigungen.md
      - 6. Schleifen: mini-games/06-schleifen.md
      - 7. Listen: mini-games/07-listen.md
      - 8. Funktionen: mini-games/08-funktionen.md
      - 9. Final Game: mini-games/09-final-game.md
